### ISSUE TITLE
Add thread metadata to crash metadata

### ISSUE THREAD

**Issue by orrc** [bitstadium/HockeySDK-Android#102]
I got a crash with the usual metadata shown below.

In cases like this (and in general), it would be useful to have more information about the thread the exception was thrown on.

So if at least the thread name could be added to this metadata, that would be handy.

```
Package: com.foo.bar
Version Code: 123
Version Name: 1.2.3
Android: 6.0
...
Date: Sat Nov 07 09:18:22 MEZ 2015

java.util.concurrent.TimeoutException: android.os.BinderProxy.finalize() timed out after 10 seconds
	at android.os.BinderProxy.destroy(Native Method)
	at android.os.BinderProxy.finalize(Binder.java:459)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by ranterle** [comment]
Thanks @orrc for the suggestion. I'll be tracking this as a feature request.
Also always feel free to hack away on a PR for this.
