### ISSUE TITLE
CrashManager.register() requires an Activity Context, not just any Context

### ISSUE THREAD

**Issue by gregschlom** [bitstadium/HockeySDK-Android#11]
Trying to call CrashManager.register() with an Application context will lead to the following crash everytime we try to launch the application with crash files to send:

02-13 14:01:11.976: ERROR/AndroidRuntime(7835): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to resume activity {com.foo.app/com.foo.app.MyActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2742)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2771)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5039)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:246)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
        at android.app.Dialog.show(Dialog.java:281)
        at net.hockeyapp.android.CrashManager.showDialog(CrashManager.java:345)
        at net.hockeyapp.android.CrashManager.execute(CrashManager.java:160)
        at net.hockeyapp.android.CrashManager.register(CrashManager.java:110)
        at net.hockeyapp.android.CrashManager.register(CrashManager.java:97)
        at com.foo.app.MyApp.checkForCrashes(MyApp.java:37)
        at com.foo.app.MyActivity.onResume(MyActivity.java:109)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1185)
        at android.app.Activity.performResume(Activity.java:5182)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2732)
        ... 12 more

Passing in an Activity instance rather than an Application instance fixes the issue

**Comment by niedzielski** [comment]
I just hit this case wanting to register for crashes in Application.onCreate(). It seems like the API should advertise that an Activity, not just Context, is needed, even if that requires breaking apart the register method, adding a second method with a new name, or overloading it. The docs are a little misleading:

> context - The context to use. Usually your Activity object.

**Comment by ashtom** [comment]
@niedzielski You can use a context if you automatically submit crashes. Maybe we should do this automatically when the class is context, i.e. if context instanceOf Context, then auto send crashes no matter what the listener says.

**Comment by ranterle** [comment]
@ashtom we need to update the docs to be more specific in that regard

**Comment by niedzielski** [comment]
@ashtom I know there are plenty of ways to work around it, but the API is _surprising_ which is bad. In my specific use case, the user must be in control of whether the data is sent or not, so using the HockeyApp UI makes the most sense. The workaround in our codebase that I'm currently planning to use is to call CrashManager.initialize() in Application.onCreate() and CrashManager.register() in our base Activity's. This gives our app maximum crash coverage without missing out on the HockeyApp UI. If we had a minSdkVersion of 14, I would probably instead register for Application lifecycle events and call CrashManager.register() in the onActivityCreated() callback.

Using instanceof to check the Context type is better than the current implementation which throws away type safety but would still be surprising. Perhaps more so because what's more obvious that something isn't working right than a crash?

I think this whole mess stems from a more fundamental limitation of Android Dialogs. They require an Activity (and actually make the same only Context is needed claim in their signature). Another odd thing is that, as part of the setup instructions, I added a HockeyApp UpdateActivity to the manifest. I don't know the details of crash time limitations, but it would seem that another Activity could be made (and added to the manifest) instead of, or in addition to, a dialog which would prevent this error in the first place. Or maybe there's an even better solution.

**Comment by ranterle** [comment]
@niedzielski if you follow our [integration docs](https://github.com/bitstadium/HockeySDK-Android#setup) registering the managers from your main activity is actually the recommended way to do.
Regarding your other ideas: We are actively working on an aar-build of the SDK which allows us to integrate our necessary activities right from the library without anything to do on your end as an SDK user. Will look into those kinds of solutions, provided they work for the whole supported version range.

**Comment by niedzielski** [comment]
@ranterle, makes sense. Your integration docs describe well how to listen for crashes in Activities but, to be clear, that's not the issue here. I want to listen for crashes in the Application as well as provide users your great send report UI. Currently, without implementing a workaround along the lines I described above, there's no way to have _both_ UI and pre or no-Activity Application crash handling.

Looking forward to the aar!
