### ISSUE TITLE
FeedbackManager.takeScreenshot(this)

### ISSUE THREAD

**Issue by TarekMowafy** [bitstadium/HockeySDK-Android#151]
I cant take a screenshot using this method.

`FeedbackManager.setActivityForScreenshot(Activity.this);                    FeedbackManager.takeScreenshot(this);
FeedbackManager.showFeedbackActivity(this);`

i get this error 
`             java.io.FileNotFoundException: /storage/emulated/0/HockeyApp/com.dbp.Activity.jpg: open failed: ENOENT (No such file or directory)
                                                                            at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                            at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                            at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                            at net.hockeyapp.android.FeedbackManager$2.doInBackground(FeedbackManager.java:387)
                                                                            at net.hockeyapp.android.FeedbackManager$2.doInBackground(FeedbackManager.java:383)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                            at libcore.io.Posix.open(Native Method)
                                                                            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                            at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                            at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                            at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                            at net.hockeyapp.android.FeedbackManager$2.doInBackground(FeedbackManager.java:387) 
                                                                            at net.hockeyapp.android.FeedbackManager$2.doInBackground(FeedbackManager.java:383) 
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818) `

**Comment by TarekMowafy** [comment]
should be checking if the user has granted permission of external storage
