### ISSUE TITLE
PaintActivity Crash

### ISSUE THREAD

**Issue by swellner** [bitstadium/HockeySDK-Android#165]
I have lots of crashes from an device which is called "Full Android on Emulator" with the PaintActivity. I think this device is a monkeyrunner from Google. The monkeyrunner starts all activities and the PaintActivity expects an extra which isn't given.

**Here is a crashlog:**

Package: XXXXXX
Version Code: 5284
Version Name: 5.284
Android: 4.1.1
Android Build: full-eng 4.1.1 JRO03R eng.john.20160603.092221 test-keys
Manufacturer: unknown
Model: Full Android on Emulator
Thread: main-1
CrashReporter Key: 50F4AE5B-594A-B426-DCA4-D81E15C32B3E35EF291A
Start Date: Mon Jun 27 10:15:04 PDT 2016
Date: Mon Jun 27 10:15:16 PDT 2016

java.lang.RuntimeException: Unable to start activity ComponentInfo{XXXXXX/net.hockeyapp.android.PaintActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
    at android.app.ActivityThread.access$600(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4847)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:535)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at net.hockeyapp.android.PaintActivity.onCreate(PaintActivity.java:49)
    at android.app.Activity.performCreate(Activity.java:5187)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
    ... 11 more

**Comment by ranterle** [comment]
Thanks @swellner, for reporting this issue. I'll be looking into preventing this NPE from happening in this rare scenario.

**Comment by MKevin3** [comment]
This happens to us as well. Every new release we do we have to put up with rejecting these bugs from JIRA as they constantly reappear.

**Comment by johnryan** [comment]
@ranterle any update on this?

**Comment by ranterle** [comment]
@johnryan Sorry for the delay - working on this now. I can't promise anything but hope for a timely fix and release.

**Comment by ranterle** [comment]
The fix should already be live in 4.0.3 and later releases: https://github.com/bitstadium/HockeySDK-Android/blob/4.0.3/hockeysdk/src/main/java/net/hockeyapp/android/PaintActivity.java#L49-L52
