### ISSUE TITLE
App updating does not work when targeting the API 24 on Android N

### ISSUE THREAD

**Issue by candrews** [bitstadium/HockeySDK-Android#167]
When targeting API 24 and running on an Android N device, the update manager's installation feature doesn't work.

UpdateManager will download the APK from hockeyapp (including requesting permission to access external storage), but then it crashes with [FileUriExposedException](https://developer.android.com/reference/android/os/FileUriExposedException.html). Here's the stack trace:
``
Process: com.censored.android, PID: 29021
android.os.FileUriExposedException: file:///storage/emulated/0/Download/2e5b188e-41fc-45ed-9a50-d5b67bcfa515.apk exposed beyond app through Intent.getData()
   at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
   at android.net.Uri.checkFileUriExposed(Uri.java:2346)
   at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
   at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
   at android.app.Activity.startActivityForResult(Activity.java:4224)
   at android.app.Activity.startActivityForResult(Activity.java:4183)
   at android.app.Activity.startActivity(Activity.java:4507)
   at android.app.Activity.startActivity(Activity.java:4475)
   at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:197)
   at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:34)
   at android.os.AsyncTask.finish(AsyncTask.java:660)
   at android.os.AsyncTask.-wrap1(AsyncTask.java)
   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6077)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
``

This issue can be easily reproduced by creating an app targeting API 24, running the app on Android N, and calling `net.hockeyapp.android.UpdateManager.register(this)` from the main activity's `onCreate(Bundle)` method.

**Comment by candrews** [comment]
Here's a nice explanation of what the problem is, why Google changed the behavior, and how to fix it: https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by ranterle** [comment]
Thanks for the report and the detailed description - I will be looking into a fix.

**Comment by ranterle** [comment]
There is one issue with the suggested approach: It depends on support-v4 being present for the `FileProvider` class. Will have to find another way around this.
