### ISSUE TITLE
E/StrictMode: http connection resource leak when sending a tracking event

### ISSUE THREAD

**Issue by mingchen** [bitstadium/HockeySDK-Android#178]
**SDK Version:** 4.1.0
**OS:** Android 6.0

**Description:**

http connection resource leak when call `MetricsManager.trackEvent(eventName)` sending a tracking event. The following the strict mode detail message.

```
E/StrictMode: A resource was acquired at attached stack trace but never released. 
See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'close' not called
 at dalvik.system.CloseGuard.open(CloseGuard.java:180)
 at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:288)
 at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
 at com.android.okhttp.Connection.connect(Connection.java:143)
 at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
 at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
 at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
 at net.hockeyapp.android.metrics.Sender.getWriter(Sender.java:398)
 at net.hockeyapp.android.metrics.Sender.logRequest(Sender.java:320)
 at net.hockeyapp.android.metrics.Sender.send(Sender.java:141)
 at net.hockeyapp.android.metrics.Sender.sendAvailableFiles(Sender.java:126)
 at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:86)
 at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:82)
 at android.os.AsyncTask$2.call(AsyncTask.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at java.lang.Thread.run(Thread.java:818)
```

**Comment by ranterle** [comment]
Hi @mingchen - thanks for reporting this. I'll work on reproducing this and will include a fix in the next release.

**Comment by mingchen** [comment]
Hi @ranterle Thank you for your quick response and fix!

**Comment by ranterle** [comment]
@mingchen Can you send us steps to reproduce the issue? We don't get any issues like this when running a test app with StrictMode.

**Comment by ranterle** [comment]
Closing this as non-reproducible as of now. Please reopen this if it occurs again.
