### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by jaredsburrows** [bitstadium/HockeySDK-Android#182]
## Hockey app:
4.1.1, 4.0.1

## Android: 
6.0.1

## Manufacturer: 
samsung

## Model: 
SM-N910W8

## Exception:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at net.hockeyapp.android.metrics.Persistence.isFreeSpaceAvailable(Persistence.java:248)
	at net.hockeyapp.android.metrics.Persistence.persist(Persistence.java:80)
	at net.hockeyapp.android.metrics.Channel.synchronize(Channel.java:91)
	at net.hockeyapp.android.metrics.Channel.enqueue(Channel.java:72)
	at net.hockeyapp.android.metrics.Channel.enqueueData(Channel.java:141)
	at net.hockeyapp.android.metrics.MetricsManager$1.doInBackground(MetricsManager.java:340)
	at net.hockeyapp.android.metrics.MetricsManager$1.doInBackground(MetricsManager.java:334)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```

**Comment by ranterle** [comment]
Hi @jaredsburrows,
thanks for providing the extensive details on the crash. We are looking into this.

**Comment by jaredsburrows** [comment]
@ranterle Any update on this?

**Comment by jaredsburrows** [comment]
`listFiles` returns `null` - https://github.com/bitstadium/HockeySDK-Android/blob/cd5b3e9af812fba78f075de2453dd371f4a01b81/hockeysdk/src/main/java/net/hockeyapp/android/metrics/Persistence.java#L277

**Comment by ranterle** [comment]
We have not yet encountered this in our internal testing, thanks for the PR - looking at it now.
