### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by jaredsburrows** [bitstadium/HockeySDK-Android#183]
## Hockey app:
4.0.1

## Android: 
5.0.2

## Manufacturer: 
motorola

## Model: 
Nexus 6

## Exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at net.hockeyapp.android.FeedbackActivity$FeedbackHandler.handleMessage(FeedbackActivity.java:792)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5273)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by jaredsburrows** [comment]
## Android: 
4.4.2

## Manufacturer: 
LGE

## Model: 
Nexus 5

## Exception:
```
java.lang.NullPointerException
	at net.hockeyapp.android.FeedbackActivity$FeedbackHandler.handleMessage(FeedbackActivity.java:792)
	at android.os.Handler.dispatchMessage(Handler.java:127)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5122)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ranterle** [comment]
Hi @jaredsburrows, can you post steps to reproduce as well as your integration code here or in our [support channel](https://support.hockeyapp.net)?

**Comment by jaredsburrows** [comment]
I am not sure how to reproduce them. These seem like simply null check or initialization errors. These errors were caught from hockeyapp using hockeyapp. We recently upgraded to `4.1.1`, so I am hoping that these can easily be fixed or are already fixed.

**Comment by jaredsburrows** [comment]
This maybe fixed in master: https://github.com/bitstadium/HockeySDK-Android/blob/6564ca9563eb8559abd9a9b9e6672403bce7c262/hockeysdk/src/main/java/net/hockeyapp/android/FeedbackActivity.java#L792.

**Comment by johnshardman** [comment]
Different stack trace showing, but same exception when calling ShowFeedbackActivity using v4.1.0 of the HockeySDK.Xamarin NuGet package.

Calling:
HockeyApp.Android.FeedbackManager.ShowFeedbackActivity(MainActivity.TheInstance);

Results in:
Java.Lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/corlib/System.Diagnostics/Debugger.cs:122,-1	C#
>	0x6 in Android.Runtime.UncaughtExceptionHandler.UncaughtException at /Users/builder/data/lanes/3511/ce955cc0/source/xamarin-android/src/Mono.Android/Android.Runtime/UncaughtExceptionHandler.cs:43,4	C#
 	0x1C in Java.Lang.Thread.IUncaughtExceptionHandlerInvoker.n_UncaughtException_Ljava_lang_Thread_Ljava_lang_Throwable_ at /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.Thread.cs:226,5	C#
 	0x1D in object.5aca42cd-1b7b-4b16-affb-c4eb32f66744	C#
