### ISSUE TITLE
java.lang.NullPointerException 	at net.hockeyapp.android.metrics.Persistence.isFreeSpaceAvailable

### ISSUE THREAD

**Issue by jaredsburrows** [bitstadium/HockeySDK-Android#184]
## Hockey app:
4.1.1

## Android: 
4.4.2

## Manufacturer: 
samsung

## Model: 
SM-G386W

## Exception:
```
java.lang.NullPointerException
	at net.hockeyapp.android.metrics.Persistence.isFreeSpaceAvailable(Persistence.java:277)
	at net.hockeyapp.android.metrics.Persistence.persist(Persistence.java:92)
	at net.hockeyapp.android.metrics.Channel.synchronize(Channel.java:112)
	at net.hockeyapp.android.metrics.Channel$SynchronizeChannelTask.run(Channel.java:205)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by jaredsburrows** [comment]
Similar to #https://github.com/bitstadium/HockeySDK-Android/issues/182

**Comment by jaredsburrows** [comment]
`listFiles` returns `null` - https://github.com/bitstadium/HockeySDK-Android/blob/cd5b3e9af812fba78f075de2453dd371f4a01b81/hockeysdk/src/main/java/net/hockeyapp/android/metrics/Persistence.java#L277

**Comment by johnryan** [comment]
Seeing the same issue on 6.0.1

**Comment by jaredsburrows** [comment]
Closing this as my #185 PR was merged!
