### ISSUE TITLE
File calls on Main Thread

### ISSUE THREAD

**Issue by lipeltnf-tr** [bitstadium/HockeySDK-Android#193]
We are getting several strict mode failures from HockeyApp that are all related to File calls on the UI thread.  Below are the stack traces for the 3 occurrences:

StrictMode policy violation; ~duration=64 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
at java.io.File.doAccess(File.java:281)
at java.io.File.exists(File.java:361)
at net.hockeyapp.android.CrashManager.searchForStackTraces(CrashManager.java:772)
at net.hockeyapp.android.CrashManager.hasStackTraces(CrashManager.java:209)
at net.hockeyapp.android.CrashManager.execute(CrashManager.java:170)
at net.hockeyapp.android.CrashManager.register(CrashManager.java:125)
at net.hockeyapp.android.CrashManager.register(CrashManager.java:110)

StrictMode policy violation; ~duration=65 ms: android.os.StrictMode$StrictModeDiskWriteViolation: policy=65567 violation=1
at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1223)
at libcore.io.BlockGuardOs.mkdir(BlockGuardOs.java:172)
at java.io.File.mkdirErrno(File.java:872)
at java.io.File.mkdir(File.java:863)
at net.hockeyapp.android.CrashManager.searchForStackTraces(CrashManager.java:771)
at net.hockeyapp.android.CrashManager.hasStackTraces(CrashManager.java:209)
at net.hockeyapp.android.CrashManager.execute(CrashManager.java:170)
at net.hockeyapp.android.CrashManager.register(CrashManager.java:125)
at net.hockeyapp.android.CrashManager.register(CrashManager.java:110)

StrictMode policy violation; ~duration=65 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
at java.io.File.doAccess(File.java:281)
at java.io.File.exists(File.java:361)
at android.app.ContextImpl.createFilesDirLocked(ContextImpl.java:418)
at android.app.ContextImpl.getFilesDir(ContextImpl.java:441)
at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:203)
at net.hockeyapp.android.Constants.loadFilesPath(Constants.java:129)
at net.hockeyapp.android.Constants.loadFromContext(Constants.java:98)
at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:493)
at net.hockeyapp.android.CrashManager.register(CrashManager.java:124)
at net.hockeyapp.android.CrashManager.register(CrashManager.java:110)

**Comment by ranterle** [comment]
Currently there is no way for the `CrashManager`to not do it's IO on the main thread. We're keeping the overhead as low as possible, though.
