### ISSUE TITLE
Update installation crashes since Android 7.0

### ISSUE THREAD

**Issue by aromanovsky** [bitstadium/HockeySDK-Android#205]
According to the following trace,

`android.os.FileUriExposedException: file:///storage/emulated/0/Download/91878aa3-ba9e-4179-81aa-fa14830f2637.apk exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
	at android.net.Uri.checkFileUriExposed(Uri.java:2349)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8943)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8904)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1634)
	at android.app.Activity.startActivityForResult(Activity.java:4233)
	at android.app.Activity.startActivityForResult(Activity.java:4192)
	at android.app.Activity.startActivity(Activity.java:4516)
	at android.app.Activity.startActivity(Activity.java:4484)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:226)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:63)`

the crash is caused by exposure of a raw file:// URI.
See more at:
http://stackoverflow.com/a/41663453/4874688
https://developer.android.com/about/versions/nougat/android-7.0-changes.html#sharing-files

You may want to rewrite the URI using a content:// scheme; see https://developer.android.com/training/secure-file-sharing/index.html for exact steps, in particular https://developer.android.com/training/secure-file-sharing/setup-sharing.html

**Comment by ranterle** [comment]
Hi @aromanovsky, we have looked into this, see #167 for reference.
The issue has been worked around in versions 4.0.3 and up of the SDK, please use the latest version of the SDK to get around this.

**Comment by aromanovsky** [comment]
Thank you! Will test 4.0.3 and reopen this issue if 4.0.3 does not resolve it.
