### ISSUE TITLE
isConnectedToNetwork NRE

### ISSUE THREAD

**Issue by caltseng** [bitstadium/HockeySDK-Android#218]
We've gotten a report for a crash in the SDK. 

Reason: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
File: Util.java
Class: net.hockeyapp.android.utils.Util
Method: isConnectedToNetwork
Number of crashes: 1

```
Android: 5.0.2
Android Build: CLA_PE_QB25S_P635A20V1.0.0
Manufacturer: ZTE
Model: Blade V6
Thread: main-1
CrashReporter Key: 69334208-B369-EF04-BF13-E8DF07DE6A535CDC16BE
Start Date: Tue Apr 04 13:11:01 GMT-05:00 2017
Date: Tue Apr 04 13:11:02 GMT-05:00 2017

java.lang.RuntimeException: Unable to start activity ComponentInfo{ols.microsoft.com.shiftr/ols.microsoft.com.shiftr.activity.HomeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
	at android.app.ActivityThread.access$800(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5537)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.net.IConnectivityManager$Stub$Proxy.getProcessName(IConnectivityManager.java:2523)
	at android.net.ConnectivityManager.<init>(ConnectivityManager.java:1468)
	at android.app.ContextImpl$14.createService(ContextImpl.java:472)
	at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:331)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1941)
	at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:113)
	at android.app.Activity.getSystemService(Activity.java:5041)
	at net.hockeyapp.android.utils.Util.isConnectedToNetwork(Util.java:267)
	at net.hockeyapp.android.CrashManager.sendCrashes(CrashManager.java:576)
	at net.hockeyapp.android.CrashManager.sendCrashes(CrashManager.java:564)
	at net.hockeyapp.android.CrashManager.execute(CrashManager.java:187)
	at net.hockeyapp.android.CrashManager.register(CrashManager.java:125)
	at net.hockeyapp.android.CrashManager.register(CrashManager.java:110)
	at ols.microsoft.com.shiftr.common.HockeyAppConfig.checkHockeyForCrashes(HockeyAppConfig.java:83)
	at ols.microsoft.com.shiftr.activity.DataBoundActivity.onCreate(DataBoundActivity.java:307)
	at ols.microsoft.com.shiftr.activity.BaseActivity.onCreate(BaseActivity.java:505)
	at ols.microsoft.com.shiftr.activity.HomeActivity.onCreate(HomeActivity.java:149)
	at android.app.Activity.performCreate(Activity.java:5975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 10 more
```

**Comment by TroubleMakerBen** [comment]
Hey!
We just released version 4.1.4 that comes with a fix for this.
Thanks for using HockeyApp and let me know in case you run into other issues, have some feedback, etc..
Take care!
Benny
