### ISSUE TITLE
Caused by: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by sbolotovms** [bitstadium/HockeySDK-Android#242]
# HockeyApp:
4.1.2

# Android:
Various. 6.0, 7.0 etc.

# Phone
Various. Pixel, SM-G930F etc.

# Exception:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$KeyIterator.next(HashMap.java:885)
	at net.hockeyapp.android.metrics.JsonHelper.writeDictionary(JsonHelper.java:192)
	at net.hockeyapp.android.metrics.model.EventData.serializeContent(EventData.java:138)
	at net.hockeyapp.android.metrics.model.Domain.serialize(Domain.java:41)
	at net.hockeyapp.android.metrics.JsonHelper.writeJsonSerializable(JsonHelper.java:163)
	at net.hockeyapp.android.metrics.model.Data.serializeContent(Data.java:48)
	at net.hockeyapp.android.metrics.model.Base.serialize(Base.java:63)
	at net.hockeyapp.android.metrics.JsonHelper.writeJsonSerializable(JsonHelper.java:163)
	at net.hockeyapp.android.metrics.model.Envelope.serializeContent(Envelope.java:441)
	at net.hockeyapp.android.metrics.model.Envelope.serialize(Envelope.java:344)
	at net.hockeyapp.android.metrics.Channel.serializeEnvelope(Channel.java:184)
	at net.hockeyapp.android.metrics.Channel.enqueueData(Channel.java:166)
	at net.hockeyapp.android.metrics.MetricsManager$3.doInBackground(MetricsManager.java:491)
	at net.hockeyapp.android.metrics.MetricsManager$3.doInBackground(MetricsManager.java:479)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```

**Comment by TroubleMakerBen** [comment]
Hey Sergej,

Thanks for reporting this here, too =)
I have the same question as for the other issue you reported ;)

Thx and take care!
Benny

**Comment by sbolotovms** [comment]
Hi Benjamin,

This doesn't seem like recurring issue, those are logs we're seeing happening in some of our HockeyApp reports. So unfortunately I can't provide you with repro steps.
Same for other issue.

**Comment by TroubleMakerBen** [comment]
Hi Sergei,

I see. Thanks for reporting this. We'll try to repro the issue. Keeping both open on GH.

Best,
Benjamin

**Comment by MatkovIvan** [comment]
Hi @sbolotovms.

Looks like you keep using properties object after `trackEvent` call. To fix this issue on current version you should create new collection instance per `trackEvent` call. Since next version we'll making copy of this object internally.

**Comment by TroubleMakerBen** [comment]
Version 4.1.6 is out and fixes this! 🎉
