### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sbolotovms** [bitstadium/HockeySDK-Android#243]
# HockeyApp
4.1.2

# Android
7.0

# Phone
SM-G955W, SM-G930T

# Exception
java.lang.ArrayIndexOutOfBoundsException: length=6; index=6
	at java.util.LinkedList.toArray(LinkedList.java:1104)
	at net.hockeyapp.android.metrics.Channel.synchronize(Channel.java:108)
	at net.hockeyapp.android.metrics.Channel$SynchronizeChannelTask.run(Channel.java:205)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by TroubleMakerBen** [comment]
Hey @sbolotovms =)
Thx for reporting this.

Can you provide any info on how to repro this?

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
See #242

**Comment by TroubleMakerBen** [comment]
Version 4.1.6 is out and fixes this! 🎉

**Comment by sbolotovms** [comment]
Just to confirm - you've meant 4.1.5, right?

**Comment by TroubleMakerBen** [comment]
Yes, it's 4.1.5. Sorry. 4.1.6 was the iOS SDK release. Dammit! ;)

Thx for letting me know!
