### ISSUE TITLE
FileUriExposedException

### ISSUE THREAD

**Issue by s70487s** [bitstadium/HockeySDK-Android#253]
Android: 7.1.1
android.os.FileUriExposedException: file:///storage/emulated/0/HockeyApp/1669393482556 exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8965)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8926)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
	at android.app.Activity.startActivityForResult(Activity.java:4225)
	at android.app.Activity.startActivityForResult(Activity.java:4183)
	at android.app.Activity.startActivity(Activity.java:4522)
	at android.app.Activity.startActivity(Activity.java:4490)
	at net.hockeyapp.android.views.AttachmentView$3.onClick(AttachmentView.java:266)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by TroubleMakerBen** [comment]
Hey @s70487s,

thank you! We're looking at improving on Android strict mode. Stay tuned!

Benny

**Comment by TroubleMakerBen** [comment]
Fixed as of HockeySDK-5.0.0-beta.1 =)
