### ISSUE TITLE
Crash on 5.0.0

### ISSUE THREAD

**Issue by yuriy-budiyev** [bitstadium/HockeySDK-Android#283]
java.lang.RuntimeException: Unable to destroy activity XXX}: java.lang.IllegalArgumentException: App ID must not be null.
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
	at android.app.ActivityThread.-wrap7(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: java.lang.IllegalArgumentException: App ID must not be null.
	at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:109)
	at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:553)
	at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:167)
	at ru.mail.intranet.ui.launcher.LauncherActivity.onDestroy(LauncherActivity.java:113)
	at android.app.Activity.performDestroy(Activity.java:7220)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
	... 9 more

**Comment by MatkovIvan** [comment]
You passing `null` to `appIdentifier` parameter when call `CrashManager.initialize`.
You should pass your app id.

**Comment by yuriy-budiyev** [comment]
I'm not passing null, this crach happens on UpdateManaget#unregister() method

**Comment by yuriy-budiyev** [comment]
That means that Util#getAppIdentifier(context) returns null

**Comment by MatkovIvan** [comment]
Since you call it from `onDestroy` callback, try to pass another context (that still alive at the moment).

**Comment by yuriy-budiyev** [comment]
I called this with an app context

**Comment by MatkovIvan** [comment]
`Util.getAppIdentifier` retrieves the HockeyApp app identifier from the manifest. Do you set `net.hockeyapp.android.appIdentifier`?

**Comment by yuriy-budiyev** [comment]
Yes, I specified it in my build.gradle file

**Comment by MatkovIvan** [comment]
You should add a `meta-data`-tag to your `AndroidManifest.xml` file.
See doc: https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#2-3-integrate-hockeysdk

**Comment by yuriy-budiyev** [comment]
I can see this in merged manifest. This is not 100% craches. That was one time. But in will be very bad if something like this will happen in production.

**Comment by MatkovIvan** [comment]
Could you please specify repro steps or small repro sample?

**Comment by yuriy-budiyev** [comment]
I don' remember. But i can tell that I firstly initialaize and execute it onCleate on may launcher activity with this activity as context, then initialize it on destroy with app context. As I descibed here: https://github.com/bitstadium/HockeySDK-Android/issues/280

**Comment by TroubleMakerBen** [comment]
We just released HockeySDK-Android 5.0.0. Can you check if this happens with this new release?

**Comment by yuriy-budiyev** [comment]
This crash happened only one time, and then I reverted version to 4.1.5. I will write here if something like this will happen on 5.0.0.

**Comment by TroubleMakerBen** [comment]
Okay.

I'm closing this issue, but will definitely open it again, in case it happens again.

Take care!

Benny
