### ISSUE TITLE
Unable to find explicit activity class net.hockeyapp.android.UpdateActivity

### ISSUE THREAD

**Issue by alizahid** [bitstadium/HockeySDK-Android#361]
Released an app update today, and it started crashing. Was on version 5.0.2 for several months, and it all worked fine. What changed suddenly? Updating to 5.1.0 didn't fix the problem.

Below is stacktrace.

```
FATAL EXCEPTION: main
Process: com.app, PID: 12555
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.app/net.hockeyapp.android.UpdateActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1932)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.startUpdateIntent(CheckUpdateTaskWithUI.java:156)
	at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.showDialog(CheckUpdateTaskWithUI.java:112)
	at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.onPostExecute(CheckUpdateTaskWithUI.java:60)
	at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.onPostExecute(CheckUpdateTaskWithUI.java:31)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by MatkovIvan** [comment]
Hi @alizahid 

Thanks for getting in touch.
I couldn't reproduce it in our test application. Would be great if you have reproduction steps for this issue.
Without issue reproduction, I see two possible reasons for that:
1. ProGuard related issue. Do you use it?
2. The activity context which you pass to `UpdateManager.register` is becoming invalid somehow. Could you please check out your integration code? [Doc for that](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#updatedistribution)

PS Apologies for that, we definitely should just log some distinct error message instead of an application crash.

Best,
Ivan

**Comment by alizahid** [comment]
Hey.

1. We don't use ProGuard
2. Possible. My integration code is below

```
@Override
protected void onResume() {
    super.onResume();

    UpdateManager.register(this);
}

@Override
public void onPause() {
    super.onPause();

    UpdateManager.unregister();
}
```

This code hasn't changed in months. It worked until today, when it suddenly started crashing.

I haven't added any native libraries or something either. But my guess is that an update to one of the 
several libraries I have in my project, or maybe React Native itself, caused this. I did notice that when the app opened, a phantom activity would jump and close, but I ignored it as a freak incident. Will debug further and update.

Would it help if my MainActivity was a `singleTask` so it doesn't become invalid?

I added the activity to my manifest for a workaround as shown [here](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#3-1-upgrading-from-3-6-x-to-3-7-0-or-newer)

**Comment by TroubleMakerBen** [comment]
Hi @alizahid,
Thx for getting in touch. We are unable to repro this issue and we don't have any changes since 5.0.2 that would explain what happens.
> maybe React Native itself, caused this
This sounds like you have a react-native application. We don't officially support React Native apps and our SDK is not designed for it. Are you aware that there's a wrapper specifically for RN. It's not supported by us but maybe it would help switching to that?

https://github.com/benloopcompany/react-native-hockeyapp

Best,
Benjamin

**Comment by guperrot** [comment]
Can you share the `build/intermediates/manifests/full/release/AndroidManifest.xml` or `./intermediates/manifests/full/{yourBuildFlavour}/release/AndroidManifest.xml`?

Can you also share the app `build.gradle` and the source versioned `AndroidManifest.xml` as well?

Thanks in advance.

**Comment by alizahid** [comment]
My `AndroidManifest.xml` had `tools:node="replace"` on the `application` node. This was the culprit. The generated manifest was missing everything, not just Hockey stuff.

Thank you for pointing me in the right direction. Sorry for the trouble!

**Comment by TroubleMakerBen** [comment]
No worries @alizahid, I'm glad you figured things out. Thx for using HockeyApp.
