### ISSUE TITLE
Cannot receive any callback in UpdateManagerListener when Exception

### ISSUE THREAD

**Issue by rockry** [bitstadium/HockeySDK-Android#362]
Sometimes I cannot receive any callback in UpdateManagerListener with same Wi-Fi connection.
After Exception, CheckUpdateTask is dead. So cannot call onPostExecute.

I cannot proceed next procedure without callback.
Because update pop-up is over-wrapped when we need to update if I proceed next procedure without callback.
Can you check this issue?

```
E/HockeyUpdate: Could not fetch updates although connected to internet
     java.io.InterruptedIOException: thread interrupted
         at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
         at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
         at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
         at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
         at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
         at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
         at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:783)
         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
         at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:112)
         at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:38)
         at android.os.AsyncTask$2.call(AsyncTask.java:305)
         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
         at java.lang.Thread.run(Thread.java:761)
```

**Comment by MatkovIvan** [comment]
Hi @rockry

Thanks for getting in touch.
It's probably related to https://github.com/bitstadium/HockeySDK-Android/issues/343#issuecomment-367406005
> `unregister()` **breaks**  checking updates process and you can see this error message in logs. If you get it always please make sure **you do not call** `unregister()` immediately (or very shortly) after appication start (`register()` call).

Please let me know if it isn't your case or you have reproduction steps for this issue.

Best,
Ivan

**Comment by rockry** [comment]
It works, Ivan.
I didn't find the issue carefully.
Thank you for your kind response.
