### ISSUE TITLE
CheckUpdateTask crash

### ISSUE THREAD

**Issue by ardmn** [bitstadium/HockeySDK-Android#372]
Hello , I have problem:

``
E/HockeyUpdate: Could not fetch updates although connected to internet
                                                                        java.io.InterruptedIOException: thread interrupted
                                                                            at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
                                                                            at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
                                                                            at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
                                                                            at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
                                                                            at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
                                                                            at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:60)
                                                                            at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1118)
                                                                            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:951)
                                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
                                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
                                                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:235)
                                                                            at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                            at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                            at net.hockeyapp.android.d.b.a(Unknown Source)
                                                                            at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:96)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
``

I find whis after telegram blocking in Russia : (  Work only with vpn ...

**Comment by Corical** [comment]
Is this maybe because update is uploaded to CDN (default way) ? Are you hosting your update APK on a server where you are sure you have access to ?

**Comment by jwallra** [comment]
Hi @ardmn - if it's true that the issue is related to the blocking of Telegram services, there's nothing we can do about it.  I don't have telegram myself but I'm told there is a bot https://t.me/krnshowtimebot which can tell you if a given IP address is blocked.  Check the IP address of your .hockeyapp.com site, and then send the bot `/overlaps your_IP_address`.

Again, I don't have Telegram and can't verify exactly how this works, but check and see if your IP address matches one of the ones blocked.  If it isn't, get back to me and I'll try to do some further investigation.

**Comment by ardmn** [comment]
Now all is ok but Have I any way to catch this exeption without app crash (for the future) ? I starts  fetching updates in not same thread where an exception was throw . Some advice, please, on what to do. :)

**Comment by ardmn** [comment]
@MatkovIvan  Really , you are right . Sorry .

**Comment by MatkovIvan** [comment]
No problem, please don't hesitate to contact us again if you have any questions or issues.
