### ISSUE TITLE
Android O StrictMode: Untagged socket detected

### ISSUE THREAD

**Issue by seniorpepe** [bitstadium/HockeySDK-Android#385]
As of Android O, if StrictMode is enabled with VmPolicy detectAll(), an untagged socket violation is thrown:

    java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
        at libcore.io.IoBridge.socket(IoBridge.java:667)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
        at java.net.Socket.createImpl(Socket.java:484)
        at java.net.Socket.getImpl(Socket.java:547)
        at java.net.Socket.setSoTimeout(Socket.java:1175)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at net.hockeyapp.android.metrics.Sender.getWriter(Sender.java:422)
        at net.hockeyapp.android.metrics.Sender.logRequest(Sender.java:346)
        at net.hockeyapp.android.metrics.Sender.send(Sender.java:146)
        at net.hockeyapp.android.metrics.Sender.sendAvailableFiles(Sender.java:125)
        at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:85)
        at net.hockeyapp.android.metrics.Sender$1.doInBackground(Sender.java:81)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

**Comment by seniorpepe** [comment]
can you allow to pass our own SocketFactory ?

**Comment by seniorpepe** [comment]
Great! 10x for the prompt response, when is the next release due for ?

**Comment by elamalani** [comment]
@seniorpepe We are going to release the SDK once Android P is officially supported.
