### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by GregSantulli** [bitstadium/HockeySDK-Android#386]
Registering the UpdateManager causes the below exception.
net.hockeyapp.android:HockeySDK:5.1.0
Android 7.0
Moto G5
targetSdkVersion 27
downgrading the Hockey SDK does not fix it. 

```java
    android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class TextView
    Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=500
        at android.content.res.StringBlock.get(StringBlock.java:66)
        at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:459)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1229)
        at android.content.res.TypedArray.getString(TypedArray.java:219)
        at android.support.v7.widget.TintTypedArray.getString(TintTypedArray.java:142)
        at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:243)
        at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:165)
        at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:82)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
        at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
        at android.widget.Toast.makeText(Toast.java:400)
        at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.showDialog(CheckUpdateTaskWithUI.java:111)
        at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.onPostExecute(CheckUpdateTaskWithUI.java:60)
        at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.onPostExecute(CheckUpdateTaskWithUI.java:31)
        at android.os.AsyncTask.finish(AsyncTask.java:660)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
````

**Comment by guperrot** [comment]
Hi, can you share your `AndroidManifest.xml` file and how are you initializing and integrating the SDK?

**Comment by guperrot** [comment]
I cannot reproduce the issue on Android 7.0, you can find my test app at https://github.com/guperrot/hockeyapp-blank-update-android if you run it from Android Studio on Android 7.0 it will show an update dialog to download the version 1.1 that I uploaded to set up that test.

Please compare my code and your code.

**Comment by MatkovIvan** [comment]
Hi @GregSantulli,
This is probably due to a known Google issue: https://issuetracker.google.com/issues/64053344
Do you change the font in your styles?

**Comment by GregSantulli** [comment]
@MatkovIvan that worked! Good catch, thank you! 

I had: 
```xml
<style name="MyTheme" parent="Theme.AppCompat.Light.NoActionBar">
    ...
    <item name="android:fontFamily">sans-serif-light</item>
    ...
</style>
```
in `styles.xml`

I changed it to use a string resource by adding 
```xml
<string name="sans_serif_light" untranslateable="true">sans-serif-light</string>
```
to `strings.xml`, then changing the style to 
```xml
<item name="android:fontFamily">@string/sans_serif_light</item>
```

Thank you!
