### ISSUE TITLE
Crash while sending feedback

### ISSUE THREAD

**Issue by stari4ek** [bitstadium/HockeySDK-Android#389]
I've got next crash among others which comes from HockeyApp itself
```
Android: 7.1.2
Android Build: T5ZP1076
Manufacturer: Amlogic
Model: T95ZPLUS
Thread: AsyncTask #15-382
CrashReporter Key: ff419900-6c6d-448e-bd77-1e21e3f0f1e2
Start Date: 2018-07-28T21:11:54.510Z
Date: 2018-07-28T21:17:32.986Z

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at net.hockeyapp.android.tasks.SendFeedbackTask.clearTemporaryFolder(SendFeedbackTask.java:182)
	at net.hockeyapp.android.tasks.SendFeedbackTask.doInBackground(SendFeedbackTask.java:150)
	at net.hockeyapp.android.tasks.SendFeedbackTask.doInBackground(SendFeedbackTask.java:33)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```

Most probably the problematic part is:
```
            File[] screenshots = hockeyAppStorageDir.listFiles(new FilenameFilter() {
                public boolean accept(File dir, String name) {
                    return name.endsWith(".jpg");
                }
            });
            for (File screenshot : screenshots) {
```

Based on analysis of `File.listFiles` there're paths when null can be returned.

**Comment by jaelim-ms** [comment]
Thanks for reporting a bug. Will take a look at the issue.
