### ISSUE TITLE
No update available on android 5.0.2 Sony Xperia Z1 Compact D5503

### ISSUE THREAD

**Issue by AntonioCappiello** [bitstadium/HockeySDK-Android#404]
Hi Guys,
I am trying to understand why my production app neither see updates or able to send feedbacks via the hockeapp sdk. This happen only on a Sony Xperia Z1 Compact D5503 device with Android 5.0.2. 

On other tests devices (samsung, lg, motorola) with various android versions (from 6 to 9go) and with the same production app then it works just fine.

Is there any known bug related to the sony manufacturer or android 5.0.2 which prevent the hockeyapp sdk to work properly?

**Comment by guperrot** [comment]
Hi, can you add `HockeyLog.setLogLevel(Log.VERBOSE);` before any call to any manager `register` method and share the Android logcat logs after testing the failed scenarios?

**Comment by AntonioCappiello** [comment]
this is what I see in the log (same for sdk v.5.0.4 and 5.1.0):
E/HockeyUpdate: Could not fetch updates although connected to internet
    java.net.ConnectException: failed to connect to sdk.hockeyapp.net/127.0.0.10 (port 443): connect failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.connect(IoBridge.java:128)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
        at java.net.Socket.connect(Socket.java:887)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
        at com.android.okhttp.Connection.connect(Connection.java:148)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
        at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:110)
        at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:38)
        at android.os.AsyncTask$2.call(AsyncTask.java:297)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
        at libcore.io.Posix.connect(Native Method)
        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:141)
        at libcore.io.IoBridge.connect(IoBridge.java:126)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
        at java.net.Socket.connect(Socket.java:887) 
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139) 
        at com.android.okhttp.Connection.connect(Connection.java:148) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106) 
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25) 
        at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:110) 
        at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:38) 
        at android.os.AsyncTask$2.call(AsyncTask.java:297) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by MatkovIvan** [comment]
Hi @AntonioCappiello,

It looks like just network connection issue. Please make sure that the device has access to the internet.   Also, HTTPS will not work with wrong date/time settings on your device, please check it as well.

Best,
Ivan

**Comment by MatkovIvan** [comment]
Do you have any firewall/proxy or something else in your device/network configuration? Are websites accessible through a browser on this device?
I found that [similar issue](https://stackoverflow.com/a/23632465/1703290) was caused by firewall.

**Comment by AntonioCappiello** [comment]
Hi @MatkovIvan, first of all thanks for your answer. 

Other devices within the same network are able to connect to the hockey app api without any problem. 

I would exclude the internet reachability problem because the same app which integrates the hockeyapp sdk is able to access internet and also to connect to other api's outside. 

Also changing wifi networks, or switching to mobile data doesn't make any difference.

I have tried to find any network settings that could block some connection on the device itself but I could't find any.

In the log error which I have posted above, I see this line "**sdk.hockeyapp.net/127.0.0.10 (port 443)**" and the ip address looks a bit weird to me. Is it meant to be like that? does the sdk creates it's own local web server on the localhost?

**Comment by ElektrojungeMS** [comment]
The SDK does not create it's own local web server. This is odd. Any chance that you are using a fork and not the official SDK?

**Comment by guperrot** [comment]
The host name should not resolve to 127.0.0.10, that's probably a DNS configuration issue for this device.

Can you add this test code snippet to confirm the issue:

```
        HockeyLog.setLogLevel(Log.VERBOSE);
        new Thread() {

            @Override
            public void run() {
                try {
                    HockeyLog.debug("address=" + Inet4Address.getByName("sdk.hockeyapp.net").getHostAddress());
                } catch (UnknownHostException e) {
                    HockeyLog.error("Could not resolve sdk.hockeyapp.net", e);
                }
            }
        }.start();
```

And then check debug logs for Hockey App.

Expected:

```
D/HockeyApp: address=52.23.116.87
```

If you have `127.0.0.10` then your device has a DNS issue.

**Comment by AntonioCappiello** [comment]
Hi @guperrot thanks for your help and sorry for the late response, I have been busy with the DroidconUK those days :-) 

Anyway, I have tested your suggestion on 2 devices so far, one reports an address from the list above (52.201.116.71) another one reports a new address: 34.194.184.22 which is also valid because the sdk works fine on that device. Did you know about the last address?

Shortly I will have the result of the test also on the Sony Xperia Z1 Compact D5503. I will post another comment in a few hours.

**Comment by AntonioCappiello** [comment]
Last update. I have tried several apps to change DNS settings on the phone, and I have also tried to manually change the wifi DNS settings by using a static ip configuration. In all cases I have used the google DNS. When I run the app, the hockeyapp sdk resolves always to 127.0.0.10, only on that phone. I am starting to think that is an issue in android 5.0.2, but I don't have other devices with same android version to confirm. 

Not sure what else to try. if you have any tips please suggest.

**Comment by AntonioCappiello** [comment]
Thank you very much @guperrot You were right. The host file on that phone was quite strange indeed. It had a lot of entries for ad-related sites and for some reason also the hockeyapp sdk too. They were all resolving to 127.0.0.10, I guess to prevent loading ads on the phone. But I have no idea how that host file was like that, we don't have any non-factory app on that phone, we use it only for testing. Really strange. 

Anyway, after a lot of struggle I was able to push on that not rooted device a new host file (without the hockeyapp entry) and then the app started to work as expected!

**Comment by guperrot** [comment]
You're welcome, glad you could make it work.

**Comment by pradipvadher** [comment]
i am facing the same issue, but i don't have device, how can i solve this issue, one of my tester is facing this issue?

**Comment by russelarms** [comment]
@pradipvadher have you did something that was recommended on this topic from the comments above?
Also, please provide more details on your issue.
