### ISSUE TITLE
SSL exception on Android 4 devices

### ISSUE THREAD

**Issue by kmspop** [bitstadium/HockeySDK-Android#418]
Can't update the app on Android 4.4.2 devices that we have in our many different office locations.
UpdateManager used to work a couple of weeks ago on Android 4 devices, but at some point, this stopped working throwing SSL exception all together.
Has anything changed from your side?
UpdateManager still works on Android 6 and other mobile devices. Just not on Android 4 devices.

E/HockeyUpdate: Could not fetch updates although connected to internet
    javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb95d3b90: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
        at com.android.okhttp.Connection.connect(Connection.java:107)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
        at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:112)
        at net.hockeyapp.android.tasks.CheckUpdateTask.doInBackground(CheckUpdateTask.java:39)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by MatkovIvan** [comment]
Hi @kmspop,

This is due to lack of TLS 1.2 support in old versions of Android by default. The backend has been updated to TLS 1.2 to avoid security issues.

The simplest, most secure solution at the moment might be to require Android 5.0 and above.

We're tracking this as a bug, and will post the updates regarding this here.

Thanks,
Ivan

**Comment by guperrot** [comment]
TLS1.0/1.1 have been enabled again on server side until SDKs are updated.

**Comment by adamKasapakis** [comment]
Hello,
Is there any change on TLS?
We have an app released with Hockey SDK 5.0.3, and on local test on Android 4.1.2 we have this issue and the in app dialog doesn't show.
Is TLS 1.0/1.1 removed again?

Thanks

**Comment by MatkovIvan** [comment]
@adamKasapakis 
https://status.hockeyapp.net/incidents/hzh73569cdlf https://www.hockeyapp.net/blog/2019/07/07/deprecation-of-tls-10-and-11.html

> ## Deprecation of TLS 1.0 and 1.1
> 2019-07-07
> HockeyApp is deprecating support for TLS 1.0 and 1.1 as part of our continuous efforts to improve security for our customers. Support for TLS 1.0 and 1.1 will be discontinued on September 1st and clients will be obligated to connect to HockeyApp with TLS version 1.2 or greater.
> 
> To Enable TLS 1.2 for Android 4.x devices you have to update the HockeySDK to the latest available version (5.2.0).

**Comment by MatkovIvan** [comment]
Closing since it's fixed in 5.2.0
