### ISSUE TITLE
UpdateFragment Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by YoungjaeKim** [bitstadium/HockeySDK-Android#426]
Hi.
I've got an issue that `UpdateDialog` is not popped up after I click the update OK dialog. It happens randomly, so I think this could be related to Android activity lifecycle.

- HockeyApp SDK version: 5.2.0

I think this is caused by `commit()` at `UpdateActivity.java` and needs to be changed to `commitAllowingStateLoss()` according to [the stackoverflow answer](https://stackoverflow.com/questions/7469082/getting-exception-illegalstateexception-can-not-perform-this-action-after-onsa).

- https://github.com/bitstadium/HockeySDK-Android/blob/30eafc6cdded517f06d0547e835235594e289b92/hockeysdk/src/main/java/net/hockeyapp/android/UpdateActivity.java#L34

```java
2019-05-29 15:02:34.623 27677-27677/ai.clova.display.portable.app.debug E/HockeyApp: An exception happened while showing the update fragment
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1864)
        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1887)
        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
        at android.app.BackStackRecord.commit(BackStackRecord.java:646)
        at android.app.DialogFragment.show(DialogFragment.java:257)
        at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.showUpdateFragment(CheckUpdateTaskWithUI.java:136)
        at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI.access$000(CheckUpdateTaskWithUI.java:31)
        at net.hockeyapp.android.tasks.CheckUpdateTaskWithUI$3.onClick(CheckUpdateTaskWithUI.java:99)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6709)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by YoungjaeKim** [comment]
I've used `true` in below overridden listener code, but I can solve by changing it to `true`.
The `true` calls Update dialog as a `DialogFragment`, but `false` shows up the UpdateActivity.

```kotlin
override fun useUpdateDialog(context: Context?): Boolean {
    return false
}
```
