### ISSUE TITLE
Android Q support

### ISSUE THREAD

**Issue by snijsure** [bitstadium/HockeySDK-Android#432]
We are using HockeyApp SDK version 5.1.0 and when upgrading app we encounter following error on devices running Android Q beta 5.

Is there additional items one needs to include in AndroidManifest, we noticed this issue in Android Q beta 5 didn't see this in Android Q beta 3

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Android/data/XXXXXX/files/Download/fa9498a9-683e-4da5-992e-4072627628e4.apk typ=application/vnd.android.package-archive flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2051)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1709)
	at android.app.Activity.startActivityForResult(Activity.java:5192)
	at android.app.Activity.startActivityForResult(Activity.java:5150)
	at android.app.Activity.startActivity(Activity.java:5521)
	at android.app.Activity.startActivity(Activity.java:5489)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:206)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:37)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)

**Comment by MatkovIvan** [comment]
Hey @snijsure,

Thanks for getting in touch!
[`android.intent.action.INSTALL_PACKAGE`](https://developer.android.com/reference/android/content/Intent.html#ACTION_INSTALL_PACKAGE) is deprecated in Android Q, so some changes in the SDK are required.
Let's treat this issue as Android Q support request.

**Comment by snijsure** [comment]
@MatkovIvan Thanks for ACKing the issue. Is there ETA for this? Android Q is supposed to go GA in about a month?

**Comment by hamswan** [comment]
As you know Hockeyapp will be shutdown in November, We urge you to transition to Appcenter. Let us know if you have any questions related to transition.

**Comment by beatrizz** [comment]
Could you please confirm if HockeyApp SDK is going to support Android Q? If not, we won't be able to use it from the moment Q is released (which is supposed to be very soon), not from November, and we'll have to rush the transition to App Center.
Does App Center already support Android Q?
Thanks!

**Comment by hamswan** [comment]
As said before we will support AndroidQ on Appcenter SDK, however not on Hockeyapp SDK.

**Comment by guperrot** [comment]
Actually the AppCenter SDK for Java/Kotlin already supports Android Q. In-app update works on that API level. The way the AppCenter APK file is downloaded and open is different from HA. The App Center code has warnings there but they can be fixed before Android 11 and none of our testing scenario failed on Q.

**Comment by budius** [comment]
- The bug from this issue blocks pushes us to migrate to AppCenter.
- The bug from this other issue on [AppCenter HERE](https://github.com/microsoft/appcenter/issues/182) blocks us from updating to AppCenter

**Comment by MatkovIvan** [comment]
Hey @budius,
it looks like a link to "AppCenter HERE" points to _this_ thread. Could you please clarify which issue blocks you?

**Comment by budius** [comment]
@MatkovIvan my bad. When cross referencing each other I missed a copy-n-paste.
It's the bug that "public distributions" is forcing users to login to AppCenter (making it not public). https://github.com/microsoft/appcenter/issues/182

also updated on the comment.

**Comment by MatkovIvan** [comment]
Ok, got it. Yeah, we know that this feature is very expected and it will be available soon

**Comment by superneopu** [comment]
Is there any way for User to install APK from the HockeyApp SDK on Android Q ?

**Comment by AnastasiaKubova** [comment]
Hi @superneopu . As you know HockeyApp was shutdown in November. We urge you to transition to App Center. Also, it already compatible with Android Q.

**Comment by superneopu** [comment]
> Hi @superneopu . As you know HockeyApp was shutdown in November. We urge you to transition to App Center. Also, it already compatible with Android Q.

I have moved to AppCenter.

But encountered a problem on the old user Who installed an app that uses the HockeryApp SDK on Android 10 cannot update because of the "android.intent.action.INSTALL_PACKAGE" issue found by the owner

How do you solve this problem?

**Comment by superneopu** [comment]
@AnastasiaKubova I have moved to AppCenter but have problems with old users. That installs apps using the HockeryApp SDK on Android Q will not be able to update because of a problem. "android.intent.action.INSTALL_PACKAGE" by topic owner

How do you solve this problem?

**Comment by MatkovIvan** [comment]
@superneopu An update is always available for download from the portal, [tester app](https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp&hl=en), or by email link. Android Q users can install the update from these sources.
