### ISSUE TITLE
Java.Lang.RuntimeException: Adding window failed ---> Java.Lang.Exception: Transaction failed on small parcel; remote process probably died

### ISSUE THREAD

**Issue by softsan** [bitstadium/HockeySDK-Android#435]
Getting this runtime crash and its recorded by Hockey app. 
**Android: 8.0.0
Android Build: R16NW.G930R4TYSACSG1
Manufacturer: samsung
Model: SM-G930R4
Thread: main-2
Start Date: 2019-10-18T13:00:55.876Z
Date: 2019-10-18T16:31:21.763Z
Format: Xamarin**

```
java.lang.RuntimeException: Adding window failed
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
	at android.app.Dialog.show(Dialog.java:420)
	at net.hockeyapp.android.CrashManager.showDialog(CrashManager.java:637)
	at net.hockeyapp.android.CrashManager.access$100(CrashManager.java:49)
	at net.hockeyapp.android.CrashManager$2.onPostExecute(CrashManager.java:243)
	at net.hockeyapp.android.CrashManager$2.onPostExecute(CrashManager.java:216)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:761)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:841)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:918)
	... 16 more
Xamarin caused by: Java.Lang.RuntimeException: Adding window failed ---> Java.Lang.Exception: Transaction failed on small parcel; remote process probably died
   --- End of inner exception stack trace ---
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Adding window failed
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:931)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
	at android.app.Dialog.show(Dialog.java:420)
	at net.hockeyapp.android.CrashManager.showDialog(CrashManager.java:637)
	at net.hockeyapp.android.CrashManager.access$100(CrashManager.java:49)
	at net.hockeyapp.android.CrashManager$2.onPostExecute(CrashManager.java:243)
	at net.hockeyapp.android.CrashManager$2.onPostExecute(CrashManager.java:216)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:761)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:841)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:918)
	... 16 more
```

**Comment by MatkovIvan** [comment]
Thanks for reporting this. We are looking into this, but since HockeyApp is going to be shutdown in Nov, we would like you to consider moving to App Center. Please let us know if you need any help with transitioning.
