### ISSUE TITLE
NPE in FeedbackActivity on Android 5

### ISSUE THREAD

**Issue by ashtom** [bitstadium/HockeySDK-Android#58]
I just experienced a crash using a Nexus 5 running Android L running HockeySDK 3.5.0-b.4 .

What I did: I tried to send feedback in my app and attached an image to the feedback, drawing on it. Once I clicked save on the FeedbackActivity, the app crashes with the stack trace attached. Inspecting it a bit, I found out, that the default Android L File Browser does not send absolute paths, and therefore the input stream can not be created.

Using another file browser works, also using a different OS version (KitKat) works.

---- STACK TRACE ----

11-24 11:19:39.459 10002-10002/app E/HockeyApp﹕ Could not save image. 
    java.io.FileNotFoundException: /data/data/app/cache/HockeyApp/primary:Pictures/Screenshots/Screenshot_2014-11-24-10-54-29.png: open failed: ENOENT (No such file or directory) 
            at libcore.io.IoBridge.open(IoBridge.java:456) 
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
            at net.hockeyapp.android.PaintActivity.makeResult(PaintActivity.java:166) 
            at net.hockeyapp.android.PaintActivity.onOptionsItemSelected(PaintActivity.java:106) 
            at android.app.Activity.onMenuItemSelected(Activity.java:2882) 
            at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1127) 
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761) 
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152) 
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904) 
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894) 
            at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:179) 
            at android.widget.AdapterView.performItemClick(AdapterView.java:300) 
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143) 
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044) 
            at android.widget.AbsListView$3.run(AbsListView.java:3833) 
            at android.os.Handler.handleCallback(Handler.java:739) 
            at android.os.Handler.dispatchMessage(Handler.java:95) 
            at android.os.Looper.loop(Looper.java:135) 
            at android.app.ActivityThread.main(ActivityThread.java:5221) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory) 
            at libcore.io.Posix.open(Native Method) 
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186) 
            at libcore.io.IoBridge.open(IoBridge.java:442) 
            at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
            at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
            at net.hockeyapp.android.PaintActivity.makeResult(PaintActivity.java:166) 
            at net.hockeyapp.android.PaintActivity.onOptionsItemSelected(PaintActivity.java:106) 
            at android.app.Activity.onMenuItemSelected(Activity.java:2882) 
            at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1127) 
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761) 
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152) 
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904) 
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894) 
            at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:179) 
            at android.widget.AdapterView.performItemClick(AdapterView.java:300) 
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143) 
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044) 
            at android.widget.AbsListView$3.run(AbsListView.java:3833) 
            at android.os.Handler.handleCallback(Handler.java:739) 
            at android.os.Handler.dispatchMessage(Handler.java:95) 
            at android.os.Looper.loop(Looper.java:135) 
            at android.app.ActivityThread.main(ActivityThread.java:5221) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
11-24 11:19:39.527 10002-10002/app D/AndroidRuntime﹕ Shutting down VM 
11-24 11:19:39.528 10002-10002/app E/AndroidRuntime﹕ FATAL EXCEPTION: main 
    Process: app, PID: 10002 
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=-1, data=Intent { (has extras) }} to activity {app/net.hockeyapp.android.FeedbackActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference 
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3539) 
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582) 
            at android.app.ActivityThread.access$1300(ActivityThread.java:144) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:135) 
            at android.app.ActivityThread.main(ActivityThread.java:5221) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference 
            at net.hockeyapp.android.utils.ImageUtils.determineOrientation(ImageUtils.java:84) 
            at net.hockeyapp.android.views.AttachmentView.loadImageThumbnail(AttachmentView.java:286) 
            at net.hockeyapp.android.views.AttachmentView.<init>(AttachmentView.java:102) 
            at net.hockeyapp.android.FeedbackActivity.onActivityResult(FeedbackActivity.java:681) 
            at android.app.Activity.dispatchActivityResult(Activity.java:6135) 
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3535) 
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582) 
            at android.app.ActivityThread.access$1300(ActivityThread.java:144) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:135) 
            at android.app.ActivityThread.main(ActivityThread.java:5221) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by ranterle** [comment]
5.0 has been out for a while - guess we can close this.
